### ISSUE TITLE
Release flowmapblue 0.0.2

### ISSUE THREAD

**Issue by e-kotov** [FlowmapBlue/flowmapblue.R#10]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`

**Comment by e-kotov** [comment]
FYI, received CRAN comments for the initial submission:

> 
> The Description field is intended to be a (one paragraph) description of
> what the package does and why it may be useful. Please add more details
> about the package functionality and implemented methods in your
> Description text.
> 
> If there are references describing the methods in your package, please
> add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year, ISBN:...)
> or if those are not available: <https:...>
> with no space after 'doi:', 'https:' and angle brackets for
> auto-linking. (If you want to add a title as well please put it in
> quotes: "Title")
> 
> Please add \value to .Rd files regarding exported methods and explain
> the functions results in the documentation. Please write about the
> structure of the output (class) and also what the output means. (If a
> function does not return a value, please document that too, e.g.
> \value{No return value, called for side effects} or similar)
> Missing Rd-tags:
>       flowmapblue-shiny.Rd: \value
> 
> Please fix and resubmit.

**Comment by ilyabo** [comment]
Big thanks @e-kotov, great that it's published as a proper package now!

**Comment by e-kotov** [comment]
> Big thanks @e-kotov, great that it's published as a proper package now!

You are welcome and thank you! We are making good use of it in https://ropenspain.github.io/spanishoddata/index.html
