### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by e-kotov** [FlowmapBlue/flowmapblue.R#7]
@ilyabo 
Any plans if putting it on CRAN? It would play well with our upcoming https://github.com/Robinlovelace/spanishoddata . We are already using https://github.com/JohMast/flowmapper for static vis as an example use for static vis and our logo. Would be happy to use `{flowmapblue.R}` too!

**Comment by ilyabo** [comment]
Nice work! I'd try to update the package and publish it on CRAN, but I am not familiar with the R ecosystem. What do I need to do?

**Comment by e-kotov** [comment]
@ilyabo here's a guide I followed for my packages https://r-pkgs.org/release.html
It's a bit involved for the first time, if you are not familiar with the the ecosystem, many little things to take into account, but the key thing is that the package should pass R CMD Check (via `devtools::check()`). If you don't have time to do this, I can act as a maintainer (not author, of course) to the package and do all the prep and submitting work for you.

**Comment by ilyabo** [comment]
> I can act as a maintainer (not author, of course) to the package and do all the prep and submitting work for you.

That'd be great! Should I add you to the project maintainers on GitHub?

**Comment by e-kotov** [comment]
@e-kotov yes

**Comment by e-kotov** [comment]
Just to be clear, here is something I will have to change so that I can manage the submission, otherwise CRAN will be sending all comms to you:

> `cre`: the creator or maintainer, the person you should bother if you have problems. Despite being short for “creator”, this is the correct role to use for the current maintainer, even if they are not the initial creator of the package.
`aut`: authors, those who have made significant contributions to the package.
`cph`: copyright holder. This is used to list additional copyright holders who are not authors, typically companies, like an employer of one or more of the authors.

[source](https://r-pkgs.org/description.html#:~:text=the%20creator%20or%20maintainer)

So I will leave you as the `aut` and also `cph`, and add myself as `cre`. If you are OK with that, we can continue.

**Comment by ilyabo** [comment]
I'm okay with that.

**Comment by e-kotov** [comment]
@ilyabo done https://cran.r-project.org/package=flowmapblue
